### ISSUE TITLE
UTMConverter routine needs correction

### ISSUE THREAD

**Issue by danielpeter** [UtahEFD/QES-Public#1]
Please note that your UTMConverter() routine provided to convert long/lat to UTM coordinates contains two 2 mistakes:

source file: Sensor.cpp

line 866:
https://github.com/UtahEFD/QES-Winds-Public/blob/9c4ea4e6cd82a2b81d9659bc8a7745678d334e5a/src/Sensor.cpp#L866

wrong: `f3 = 15.0*(e4/256.0)*45.0*(e6/1024.0);`
correct would be: `f3 = 15.0*(e4/256.0) + 45.0*(e6/1024.0);`

line 935:
https://github.com/UtahEFD/QES-Winds-Public/blob/9c4ea4e6cd82a2b81d9659bc8a7745678d334e5a/src/Sensor.cpp#L935

wrong: `f3 = 5.0*3.0*t1 + 10.0*c1 - 4.0*pow(c1,2.0) - 9.0*ep2;`
correct would be: `f3 = 5.0 + 3.0*t1 + 10.0*c1 - 4.0*pow(c1,2.0) - 9.0*ep2;`

the above corrections could be verified by looking at the original publication:
Snyder, J.P., Map projections - a working manual, USGS professional paper 1395, 1987
https://doi.org/10.3133/pp1395

line 866 mistake/correction: see page 61, eq. 3-21 for M
line 935 mistake/correction: see page 63, eq. 8-17 for phi

the above error will lead to a positional error of ~7 m when converting lon/lat to UTM.

best regards,
daniel

**Comment by willemsn** [comment]
Thank you @danielpeter!  @BBozorgmehr -- we need to add to our list to abstract the UTM stuff so it's in a separate class.  Right now we have this function in a couple of places.  After finals, I'll try to get to this.

**Comment by fmargairaz** [comment]
This issue as been addressed in the new release (v2.0.0)
